version: '3.8'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
        
  customer-management-service:
      build:
        context: .
        dockerfile: customer-management-services/Dockerfile
      ports:
        - "8081:8080"
      depends_on:
        - kafka

  payment-processing-service:
    build:
      context: .
      dockerfile: payment-processing-services/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - kafka

  balance-services:
    build:
      context: .
      dockerfile: balance-services/Dockerfile
    ports:
      - "8083:8080"
    depends_on:
        - kafka