name: Java CI with Maven

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: compose file
        uses: hoverkraft-tech/compose-action@v1.5.1
        with:
          compose-file: docker-compose.yml
          compose-version: '3.8'
          service-name: kafka
          service-port: 9092
          service-host: localhost
          service-wait-for: 60
          service-retries: 5
          service-retry-delay: 10
          service-protocol: tcp
          service-timeout: 60
          service-verbose: true
